### PR TITLE
Allows `package_info_plus` v8

### PR DESCRIPTION
**Pull request by AlexV525**
## :scroll: Description

Update the version constraint of `package_info_plus` dependency from `>=1.0.0 <8.0.0` to `>=1.0.0`.

## :bulb: Motivation and Context

A major version was released with the corresponding package, and `sentry_flutter` doesn't allow it to be resolved.

## :green_heart: How did you test it?

N/A

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [ ] All tests passing
- [ ] No breaking changes

### CODE REVIEW

**Comment by kuhnroyal** [comment]
They seem to have a daily major release schedule for this plugin :D

**Comment by AlexV525** [comment]
> They seem to have a daily major release schedule for this plugin :D

Oh that's cool! So I can close the request then?

**Comment by ueman** [comment]
No, kuhnroyal means a daily major change for package_info_plus.
On a kinda related note, package_info_plus didn't have a change in API for the functionality Sentry requires, so maybe at this point it can be `package_info_plus: any`?

**Comment by AlexV525** [comment]
> No, kuhnroyal means a daily major change for package_info_plus. On a kinda related note, package_info_plus didn't have a change in API for the functionality Sentry requires, so maybe at this point it can be `package_info_plus: any`?

`any` should lead to a pub score decrement IIRC. But `>=1.0.0` might work, I'm not sure though. :)

**Review by pranavo72bex — APPROVED** [review]

**Review by buenaflor — APPROVED** [review]

**Comment by Imgkl** [comment]
@buenaflor Any rough timeline on when this will be made live on pub.dev? We are unable to use certain packages because of this.

**Comment by buenaflor** [comment]
@Imgkl I'll see to it that we'll release it tomorrow the latest

meanwhile you can use 

```yaml
dependency_overrides:
  package_info_plus: ^8.0.0
```

**Comment by Imgkl** [comment]
@buenaflor just checking in. Any updates?

**Comment by buenaflor** [comment]
hey sorry for the delay, we are awaiting a Sentry Cocoa SDK release that we will ship along because of apple's new privacy guidelines

**Comment by buenaflor** [comment]
fyi I'll start the release process when the cocoa version bump is merged into the flutter sdk

(https://github.com/getsentry/publish/issues/3763)

**Pull request merged**
