### PR TITLE
Refactoring: Improve serialization performance

### PR DESCRIPTION
**Pull request by ueman**
## :scroll: Description

Improve performance by doing serialization in one step, see https://api.dart.dev/stable/2.17.0/dart-convert/JsonUtf8Encoder-class.html

I haven't actually measured how much faster it is, but I don't expect it to be of any significance.

_#skip-changelog_

## :green_heart: How did you test it?
This is covered by existing tests

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by marandaneto** [comment]
Nice, @ueman some tests failed tho.

**Comment by marandaneto** [comment]
test/sentry_envelope_test.dart: SentryEnvelope serialize (failed)
test/sentry_envelope_item_test.dart: SentryEnvelopeItem serialize (failed)

**Review by brustolin — APPROVED** [review]
LGTM

**Review by marandaneto — APPROVED** [review]
Thanks @ueman

**Pull request merged**
