### PR TITLE
meta: Remove confusing example dsn

### PR DESCRIPTION
**Pull request by bruno-garcia**
@skip-changelog

### CODE REVIEW

**Review by marandaneto — APPROVED** [review]

**Comment by marandaneto** [comment]
apparently, there's a new NDK version `21.4.7075529` and CI is unhappy

**Review by philipphofmann — APPROVED** [review]
LGTM, but please prefix the PR and squash merge with `docs` or something equivalent, https://develop.sentry.dev/code-review/#type

**Comment by bruno-garcia** [comment]
This semantic commit message is more of `getsentry/sentry` thing, it's not so strict in other repos.

**Comment by bruno-garcia** [comment]
@marandaneto where can I bump NDK here?

**Comment by marandaneto** [comment]
> @marandaneto where can I bump NDK here?

right now no way how to fix it #294
they will probably fix this on the images like the other times

**Comment by bruno-garcia** [comment]
Oh I see. Main is already broken

**Pull request merged**
