### PR TITLE
mergeAttributes: deepcopy RHS Map if LHS isn't Map

### PR DESCRIPTION
**Pull request by dotdoom**

### CODE REVIEW

**Comment by dotdoom** [comment]
The problem that this PR solves is that a Map present in `environmentAttributes` gets exposed when [initially merged into `data`](https://github.com/flutter/sentry/blob/5167a5c/lib/sentry.dart#L188-L195). It is then mutated by the following `mergeAttributes` of `event` into `data`.

---

Looks like Travis build fails because it can't resolve some dependencies with Dart 2. I tested this PR by running `echo test/*.dart | xargs -n1 dart`.

**Comment by yjbanov** [comment]
I like this change! Thank you for the fix. I'll have a look at Travis asap (currently AFK).

**Comment by dotdoom** [comment]
Sent https://github.com/flutter/sentry/pull/24 for that, and rebased this PR, too.

**Review by yjbanov — APPROVED** [review]

**Comment by yjbanov** [comment]
LGTM

**Comment by yjbanov** [comment]
This is now published in version 2.1.1: https://pub.dartlang.org/packages/sentry

**Pull request merged**
