### PR TITLE
chore(v8): update to min ios version 12

### PR DESCRIPTION
**Pull request by buenaflor**
## :scroll: Description
Closes #1820 

## :bulb: Motivation and Context

#skip-changelog
## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [ ] All tests passing
- [ ] No breaking changes

### CODE REVIEW

**Comment by buenaflor** [comment]
@denrase can I get a quick review pls, wanna make sure `min_version_test` and the iOS native integration tests are green. A lot of other tests will expectedly fail since we didn't merge the current v7 branch yet

**Review by denrase — APPROVED** [review]
LGTM, CI seems to be unhappy.

On main we also set the min iOS version in pod dependenvies. We should not forget this when merging main into V8.

https://github.com/getsentry/sentry-dart/blob/24b6e601e2c8a3bc70ac06d1d0293067d3df5351/flutter/example/ios/Podfile#L47

**Comment by buenaflor** [comment]
@denrase shall we do a main merge into v8 before we finish this pr? to make sure ci is all green?

**Comment by denrase** [comment]
@buenaflor Makes sense to get main into v8 IMHO

**Pull request merged**
