### PR TITLE
Avoid dependency conflict with package_info_plus v4

### PR DESCRIPTION
**Pull request by marandaneto**
## :scroll: Description
Avoid dependency conflict with package_info_plus v4

## :bulb: Motivation and Context
Closes https://github.com/getsentry/sentry-dart/pull/1436

https://docs.flutter.dev/reference/supported-platforms#deploying-flutter

## :green_heart: How did you test it?
CI should be green

## :pencil: Checklist

- [X] I reviewed submitted code
- [ ] I added tests to verify changes
- [X] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [X] All tests passing
- [ ] No breaking changes

## :crystal_ball: Next steps
Document breaking change under sentry docs.

### CODE REVIEW

**Comment by marandaneto** [comment]
@krystofwoldrich @stefanosiano mind reviewing this one quickly? it's blocking some other PRs.

**Review by krystofwoldrich — APPROVED** [review]
LGTM 🚀 ~~I still see some jobs failing, is that just flakiness?~~

**Comment by krystofwoldrich** [comment]
@marandaneto The metrics app still needs a bum to A SDK v19.

Do I get it right, that our SDK will actually work on A SDK v16 with older Flutter? But we can test it anymore since we build in CI with the latest Flutter version.

**Review by krystofwoldrich — CHANGES_REQUESTED** [review]
@marandaneto The metrics app still needs a bum to A SDK v19.

Do I get it right, that our SDK will actually work on A SDK v16 with older Flutter? But we can test it anymore since we build in CI with the latest Flutter version.

**Comment by marandaneto** [comment]
> @marandaneto The metrics app still needs a bum to A SDK v19.
> 
> Do I get it right, that our SDK will actually work on A SDK v16 with older Flutter? But we can test it anymore since we build in CI with the latest Flutter version.

Good catch, https://github.com/getsentry/sentry-dart/pull/1440/commits/b89812ea2f4531a068ea0dffd27f21d2a78e380f

**Comment by marandaneto** [comment]
> @marandaneto The metrics app still needs a bum to A SDK v19.
> 
> Do I get it right, that our SDK will actually work on A SDK v16 with older Flutter? But we can test it anymore since we build in CI with the latest Flutter version.

Android SDK is min 14, but Flutter was 16 and now is 19.

**Review by krystofwoldrich — APPROVED** [review]
🚀

**Review by krystofwoldrich — APPROVED** [review]
🚀

**Pull request merged**
