### PR TITLE
Replace `toImage` with `toImageSync` for Flutter >= 3.7

### LINKED ISSUE #1246: Replace `toImage` with `toImageSync` for Flutter >= 3.7
### Description

https://api.flutter.dev/flutter/rendering/RenderRepaintBoundary/toImageSync.html

https://medium.com/flutter/whats-new-in-flutter-3-7-38cbea71133c

There's a performance improvement when doing that.

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

Closes #1246 

## :green_heart: How did you test it?

Ran example app on Flutter 3.3.x and 3.7.x and checked if triggering error attached a screenshot.

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by denrase** [comment]
@marandaneto Interestingly, the compiler does complain with Flutter `3.7.x`, but i can run the example app and the UI tests without problems. Is this part of the "hack"?

Bildschirm­foto 2023-02-06 um 15 20 07

**Comment by marandaneto** [comment]
> @marandaneto Interestingly, the compiler does complain with Flutter `3.7.x`, but i can run the example app and the UI tests without problems. Is this part of the "hack"?
> 
> Bildschirm­foto 2023-02-06 um 15 20 07

Is the compiler or just the IDE linter? if you can run, its not a compiler issue and this should be fine.

**Comment by ueman** [comment]
> @marandaneto Interestingly, the compiler does complain with Flutter `3.7.x`, but i can run the example app and the UI tests without problems. Is this part of the "hack"?
> 
> Bildschirm­foto 2023-02-06 um 15 20 07

I think it complains because `return (repaintBoundary as dynamic).toImageSync(pixelRatio: pixelRatio);` has a return type of `dynamic` which gets implicitly casted to `FutureOr<ui.Image>`. So I would guess `return (repaintBoundary as dynamic).toImageSync(pixelRatio: pixelRatio) as ui.Image;` should fix that warning/error.

Calling something on dynamic disables any typechecks, so return values are dynamic too.

**Comment by marandaneto** [comment]
@denrase this one still has pending comments

**Review by marandaneto — APPROVED** [review]
If CI is happy, we can merge it, thanks.

**Comment by marandaneto** [comment]
@denrase we can fix the conflict and merge it if CI is happy

**Pull request merged**
