### PR TITLE
feat: tracing without performance for dio

### PR DESCRIPTION
**Pull request by IgorKhramtsov**
## :scroll: Description

Tracing without performance was implemented for `HttpClient` in https://github.com/getsentry/sentry-dart/pull/1621 but it was never implemented for `sentry_dio` package.

## :bulb: Motivation and Context

On my project, we updated sentry to the latest version in order to get tracing without performance, but it wasn't working. Turned out this is because we are using `Dio` with `sentry_dio`. This PR resolves that issue.

## :green_heart: How did you test it?
Unit tests

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [x] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by buenaflor** [comment]
Thanks for the PR, sorry for missing the dio implementation.

Generally looks good to me. Could you also verify the changes by running our sample app if possible

**Comment by IgorKhramtsov** [comment]
Sure. 
Verified by launching the `example` app from `dio` directory with the following scenarios:
1. Run app as is - sentry-trace and baggage available in the request headers
2. Run app with commented out transaction and 0 sample rate - sentry-trace is available in the request headers.

**Review by buenaflor — APPROVED** [review]
👍  thx for the contribution! (will merge after tests pass)

**Comment by buenaflor** [comment]
this is now released in `7.16.0`

**Pull request merged**
