### PR TITLE
Feat: Support `Attachment.addToTransactions`

### LINKED ISSUE #649: Support `Attachment.addToTransactions` configuration
today attachments are sent along with transactions.
this should be configurable option, as it is on Android and iOS

https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/Attachment.java#L14

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

- Introduce `Attachment.addToTransactions` property.
- Add attachments from scope to transactions where property `addToTransactions` is `true`.

## :bulb: Motivation and Context

Closes #649

## :green_heart: How did you test it?

Added tests.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by ueman** [comment]
What about https://github.com/getsentry/sentry-dart/blob/main/flutter/lib/src/flutter_sentry_attachment.dart ?

**Comment by marandaneto** [comment]
> What about [`main`/flutter/lib/src/flutter_sentry_attachment.dart](https://github.com/getsentry/sentry-dart/blob/main/flutter/lib/src/flutter_sentry_attachment.dart?rgh-link-date=2022-01-20T15%3A31%3A35Z) ?

I was gonna say the same.

**Review by marandaneto — APPROVED** [review]
LGTM, thanks @denrase

**Comment by denrase** [comment]
@ueman @marandaneto Thx for pointing this out. Added the param and resolved the conflicts.

**Comment by marandaneto** [comment]
@brustolin wanna double-check?

**Pull request merged**
