### PR TITLE
Add isar (community fork) support

### PR DESCRIPTION
**Pull request by sbordeyne**
## :scroll: Description

This PR adds a new package: `isar_community`, which is identical (a carbon copy) to the existing `isar` package, except that it depends on the community fork for isar.

## :bulb: Motivation and Context
This is required since the main package has gone unmaintained for the last 17 months, but the community has forked and maintained it, on a separate pub repository.

The issue I opened : #2296

## :green_heart: How did you test it?

It's a carbon copy of the existing isar integration, due to it already being tested, the tests are identical, no further tests have been written. The community fork, in its 3.1 release of isar didn't break any existing APIs.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [x] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by vaind** [comment]
Is adding another package here necessary/desirable? This adds maintenance load on the Sentry SDK.

How about specifying `dependency_overrides` in apps using the isar_community fork?

**Review by vaind — CHANGES_REQUESTED** [review]
Is adding another package here necessary/desirable? This adds maintenance load on the Sentry SDK.

How about specifying `dependency_overrides` in apps using the isar_community fork?

**Comment by sbordeyne** [comment]
> Is adding another package here necessary/desirable? This adds maintenance load on the Sentry SDK.
> 
> How about specifying `dependency_overrides` in apps using the isar_community fork?

Good point, I tested using a dependency override, which seems to be working fine at first glance. I seem to recall that the codegen is a bit different though, so time will tell if it breaks or not, but at least my app compiles with that override.

A good thing to do though would be to document it in the readme of the `sentry_isar` package, I can open a pull request to add it there if you want, the gist of it is to add 

```yaml
isar_version: &isar_version 3.1.8

dependency_overrides:
  isar:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_generator:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  sentry_isar:

```

in the `pubspec.yaml`

**Comment by vaind** [comment]
> > Is adding another package here necessary/desirable? This adds maintenance load on the Sentry SDK.
> > How about specifying `dependency_overrides` in apps using the isar_community fork?
> 
> Good point, I tested using a dependency override, which seems to be working fine at first glance. I seem to recall that the codegen is a bit different though, so time will tell if it breaks or not, but at least my app compiles with that override.
> 
> A good thing to do though would be to document it in the readme of the `sentry_isar` package, I can open a pull request to add it there if you want, the gist of it is to add
> 
> ```yaml
> isar_version: &isar_version 3.1.8
> 
> dependency_overrides:
>   isar:
>     version: *isar_version
>     hosted: https://pub.isar-community.dev/
>   isar_flutter_libs:
>     version: *isar_version
>     hosted: https://pub.isar-community.dev/
>   isar_generator:
>     version: *isar_version
>     hosted: https://pub.isar-community.dev/
>   sentry_isar:
> ```
> 
> in the `pubspec.yaml`

Maybe worth updating the instructions here: https://github.com/isar-community/isar#1-add-to-pubspecyaml and it would be fixed for all plugins using isar somewhere down the dependency tree. This is not really limited to Sentry

**Pull request closed without merging**
