### PR TITLE
VendorId should be a String

### PR DESCRIPTION
**Pull request by marandaneto**
## :bulb: Motivation and Context
https://github.com/getsentry/team-mobile/issues/67

## :pencil: Checklist

- [X] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated the docs if needed
- [X] All tests passing
- [ ] No breaking changes

It's technically a breaking change but nobody should be using it directly.
Also its a bug fixing since the previous type does not work.

### CODE REVIEW

**Comment by marandaneto** [comment]
@romtsn or @markushi can we fix this on Android? otherwise the serialization would fail on Android anyway.

**Comment by krystofwoldrich** [comment]
I guess this need to wait for Android SDK.

**Comment by marandaneto** [comment]
> I guess this need to wait for Android SDK.

its in the making, no need to block the PR tho.

**Review by brustolin — APPROVED** [review]

**Comment by marandaneto** [comment]
@markushi can we cut a release on Android so we can unblock this?

**Comment by markushi** [comment]
@marandaneto the required `sentry-java` changes will be shipped with `6.7.1`, [which is about to be published.](https://github.com/getsentry/publish/issues/1573)

**Pull request merged**
