### PR TITLE
Fix: ConcurrentModificationError in when finishing span

### LINKED ISSUE #662: `ConcurrentModificationError` in when finishing span
I have a lot of reports of a `ConcurrentModificationError` coming from this for loop:
https://github.com/getsentry/sentry-dart/blob/58de5ac0943ec9bd5e15a4fdcd7a4b5ae9411585/dart/lib/src/sentry_tracer.dart#L31-L35

I believe this happens when a new span starts before the finish method is done.
It is hard to reproduce manually, but a fix I see is to make a copy of children before starting to iterate over them.

### PR DESCRIPTION
**Pull request by marandaneto**
## :scroll: Description
Fix: ConcurrentModificationError in when finishing span

## :bulb: Motivation and Context
Closes https://github.com/getsentry/sentry-dart/issues/662

## :pencil: Checklist

- [X] I reviewed submitted code
- [X] I added tests to verify changes
- [ ] I updated the docs if needed
- [X] All tests passing
- [X] No breaking changes

### CODE REVIEW

**Review by bruno-garcia — APPROVED** [review]
Lgtm but whst abour adding a diagnostics warn log

**Comment by ueman** [comment]
Also, a test would be good

**Comment by marandaneto** [comment]
> Also, a test would be good

yep, will come.
edit @ueman done

**Comment by marandaneto** [comment]
> Lgtm but whst abour adding a diagnostics warn log

right now we don't have access to the log in this class, will check if its easy, good idea.
edit: will follow up with another PR so we don't block the bugfix release

**Pull request merged**
