### PR TITLE
Use TestWidgetsFlutterBinding instead of WidgetsFlutterBinding for tests

### PR DESCRIPTION
**Pull request by marandaneto**
_#skip-changelog_

### CODE REVIEW

**Comment by ueman** [comment]
I wonder if this code snippet at the end of the file is still needed after this change.
```dart
/// Flutter >= 2.12 throws if ServicesBinding.instance isn't initialized.
ServicesBinding? getServicesBindingInstance() {
  try {
    return ServicesBinding.instance; // Maybe this should also return TestWidgetsFlutterBinding.ensureInitialized(); ?
  } catch (_) {}
  return null;
}
```

**Comment by marandaneto** [comment]
> ```dart
> .instance
> ```

This is for Flutter Stable/Beta compatibility.
How `SchedulerBinding` instance would allow to return `TestWidgetsFlutterBinding.ensureInitialized()`?
Copy paste error?

**Comment by ueman** [comment]
`TestWidgetsFlutterBinding` implements `SchedulerBinding`, so that replacement should be possible.

**Comment by marandaneto** [comment]
> `TestWidgetsFlutterBinding` implements `SchedulerBinding`, so that replacement should be possible.

Oh good catch, thanks

**Review by brustolin — APPROVED** [review]

**Pull request merged**
