### PR TITLE
Make dio experimental

### PR DESCRIPTION
**Pull request by marandaneto**
## :scroll: Description
Make dio experimental
_#skip-changelog_

## :bulb: Motivation and Context
https://github.com/getsentry/sentry-dart/issues/715

Since `dio` is a experimental feature, adding the annotation unblocks us to go GA with the other features.

## :pencil: Checklist

- [X] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated the docs if needed
- [X] All tests passing
- [X] No breaking changes

### CODE REVIEW

**Comment by ueman** [comment]
Maybe this should be pointed out in the readme?

**Review by romtsn — APPROVED** [review]
Docs are still not there right? should probably also mention that it's experimental there

**Comment by marandaneto** [comment]
> Docs are still not there right? should probably also mention that it's experimental there

no docs yet.

**Review by ueman — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
