### PR TITLE
Fix: Envelope length should be based on the UTF8 array instead of String length

### PR DESCRIPTION
**Pull request by marandaneto**
## :loudspeaker: Type of change

- [X] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description
Fix: Envelope length should be based on the UTF8 array instead of String length

## :bulb: Motivation and Context
#242

## :pencil: Checklist

- [X] I reviewed submitted code
- [X] I added tests to verify changes
- [X] All tests passing
- [X] No breaking changes

### CODE REVIEW

**Review by ueman — APPROVED** [review]
LGTM.

**Comment by ueman** [comment]
But dang, that is nasty. If I understand correctly this prevents every event which contains unicode chars from being send, right?

**Comment by marandaneto** [comment]
> But dang, that is nasty. If I understand correctly this prevents every event which contains unicode chars from being send, right?

not really, a subset of it and usually they are not part of "normal" events, but it's rather critical of course, I'm cutting a release pretty soon.

**Comment by marandaneto** [comment]
`pana` is failing but nothing has changed (works locally though), created https://github.com/axel-op/dart-package-analyzer/issues/12 and will merge it

**Pull request merged**
