### PR TITLE
Update authors and readme

### PR DESCRIPTION
**Pull request by yjbanov**
/cc @lejard-h

### CODE REVIEW

**Comment by lejard-h** [comment]
Thanks :+1: 

I am currently migrating [angular_sentry](https://pub.dev/packages/angular_sentry), could you add it to the README ?

The repo is here https://github.com/leftyio/angular_sentry, I am waiting for sentry 3.0.0 before publishing it

**Review by filiph — APPROVED** [review]
LGTM

**Comment by filiph** [comment]
Oh, sorry @lejard-h, I didn't see your comment. Feel free to submit a PR with updated README.

**Comment by yjbanov** [comment]
Oops! My bad, I thought I pushed the changes. Here's the PR: https://github.com/flutter/sentry/pull/48

**Pull request merged**
