### PR TITLE
Add a stackFrameFilter argument to SentryClient's capture

### PR DESCRIPTION
**Pull request by tom95**
Attempt no 2, description copied:

This change allows filtering sensitive frames on the client or applying custom truncation logic.

I created this in reaction to this discussion: https://forum.sentry.io/t/issue-in-flutter-project-with-stackframe-display-limit-set-to-250/5014/2

Instead of adding complex truncation options that will likely depend on the frameworks you use anyways, I opted to provide a more general callback that could also be used for things like filtering specific frames. In the case of above discussion, we'd simply cut the list passed to us to only send the topmost 250 items.

### CODE REVIEW

**Comment by tom95** [comment]
Hm. Any guidance on how to tackle the CLA bot's disapproval? It does not appear to be possible to inspect CLAs for companies via the link and the troubleshooting section on that topic contains mostly broken links :(

**Review by yjbanov — COMMENTED** [review]
The CLA bot seems happy, but `dartfmt` failed. Could you please format edited files using `dartfmt`? LGTM with a small comment.

**Comment by tom95** [comment]
Thank you for the review! I added the comment and let dartfmt do its thing.

(I chose to keep this PR over the other because this one contained actual review comments :) )

**Comment by yjbanov** [comment]
Thank you for the contribution and for your patience! :+1:

**Pull request merged**
