### PR TITLE
Pin sentry version

### LINKED ISSUE #1021: sentry_flutter 6.7.0 build fail after the release of sentry 6.11.0
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

[✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-x64, locale en-GB)
    • Flutter version 3.0.5 at /Users/timekone/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
    • Android SDK at /Users/timekone/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0-rc4
    • Java binary at: /Users/timekone/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/timekone/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/timekone/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.70.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

The version of the SDK (See pubspec.lock):
**6.7.0** **6.11.0**

---
I have the following issue:

I had a dependency on `sentry_flutter 6.7.0` (without caret symbol) which uses `SentryTracer.addMeasurements().` from the `sentry` package.
`SentryTracer.addMeasurements()` has been removed in `sentry 6.11.0`.
`sentry_flutter 6.7.0 depends` on `sentry: ^6.7.0.`. In this case, `sentry` gets automatically updated to 6.11.0.
 But sentry_flutter 6.7.0 is incompatible with sentry 6.11.0.

```
../../../../.pub-cache/hosted/pub.dartlang.org/sentry_flutter-6.7.0/lib/src/navigation/sentry_navigator_observer.dart:177:25: Error: The method 'addMeasurements' isn't defined for the class 'SentryTracer'.
 - 'SentryTracer' is from 'package:sentry/src/sentry_tracer.dart' ('../../../../.pub-cache/hosted/pub.dartlang.org/sentry-6.11.0/lib/src/sentry_tracer.dart').
Try correcting the name to the name of an existing method, or defining a method named 'addMeasurements'.
            transaction.addMeasurements(nativeFrames.toMeasurements());
                        ^^^^^^^^^^^^^^^

../../../../.pub-cache/hosted/pub.dartlang.org/sentry_flutter-6.7.0/lib/src/event_processor/native_app_start_event_processor.dart:43:26: Error: The method 'add' isn't defined for the class 'Map<String, SentryMeasurement>'.
 - 'Map' is from 'dart:core'.
 - 'SentryMeasurement' is from 'package:sentry/src/sentry_measurement.dart' ('../../../../.pub-cache/hosted/pub.dartlang.org/sentry-6.11.0/lib/src/sentry_measurement.dart').
Try correcting the name to the name of an existing method, or defining a method named 'add'.
      event.measurements.add(measurement);
```

**Steps to reproduce:**
- Run `flutter clean`, remove `pubspec.lock`
- Add `sentry_flutter: 6.7.0` dependency(without caret symbol)
- Run `flutter pub get`
- `flutter run`

**Actual result:**
- Build fail

**Expected result:**
- Successful build

### PR DESCRIPTION
**Pull request by timekone**
Resolves #1021

`flutter_sentry` and `sentry` packages versions should be in sync. Using caret symbol `^` may cause mismatch of versions and a build fail.

Example:
`sentry_flutter 6.7.0` depends on `sentry: ^6.7.0`

A user has `sentry_flutter: 6.7.0` (without caret symbol) in their pubspec.yaml. 

`sentry_flutter: 6.7.0` depends on `SentryTracer.addMeasurements()`. 
`SentryTracer.addMeasurements()` was removed in `sentry 6.11.0`.
 This means that `sentry_flutter 6.7.0` is incompatible with `sentry 6.11.0`.

### CODE REVIEW

**Comment by marandaneto** [comment]
@timekone thanks.
This [script](https://github.com/getsentry/sentry-dart/blob/main/scripts/bump-version.sh) has to be patched as well.

**Comment by kuhnroyal** [comment]
I think this may reduce the pana score, may need some adaptions as well there.

**Comment by timekone** [comment]
> I think this may reduce the pana score, may need some adaptions as well there.

Do you think so? I ran pana locally, and it returned the max score.

**Comment by marandaneto** [comment]
@timekone please add a changelog entry, so we can merge it, thanks for doing this.

**Review by marandaneto — APPROVED** [review]

**Comment by kuhnroyal** [comment]
> > I think this may reduce the pana score, may need some adaptions as well there.
> 
> Do you think so? I ran pana locally, and it returned the max score.

Ah nice, that is good. I thought pub and pana once had a warning for pinned versions in libraries.

**Pull request merged**
