### PR TITLE
Add request instead of response data in DioEventProcessor

### PR DESCRIPTION
**Pull request by kuhnroyal**
## :scroll: Description

Add request instead of response data to `SentryRequest` in `DioEventProcessor`

## :bulb: Motivation and Context

Response data may contain PII and should not be logged by the framework.
The `SentryRequest.data` is meant to contain request data. 
See discussion in https://github.com/getsentry/sentry-dart/issues/624 about PII.

## :green_heart: How did you test it?
Ran and adapted the tests

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [x] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps

CC @ueman

### CODE REVIEW

**Comment by ueman** [comment]
This looks good to me.
I still whish, that there's not only a `SentryRequest` but also a `SentryResponse`.

On mobile it makes a lot of sense to record the response since, at least in my experience, that's a lot of the times also a source of errors (https://github.com/getsentry/develop/issues/401).

Regarding PII, why does it matter? I mean response and request can contain PII?

**Review by ueman — APPROVED** [review]

**Comment by kuhnroyal** [comment]
> This looks good to me. I still whish, that there's not only a `SentryRequest` but also a `SentryResponse`.
> 
> On mobile it makes a lot of sense to record the response since, at least in my experience, that's a lot of the times also a source of errors.
> 
> Regarding PII, why does it matter? I mean response and request can contain PII?

I absolutely agree but it should be consistent in the SDK.
For me usually requests contain PII, responses contain weird validation errors which I am currently trying to manually log into `SentryRequest.other` map. But the order of `DioEventProcessor` and my custom processor can not be controlled. I need to add mine after `DioEventProcessor` somehow ...

**Comment by marandaneto** [comment]
Makes sense, since the request data is guarded by `maxRequestBodySize`, wondering if this was an oversight or if we've decided to add the response in there for some reason, @ueman ?
@ueman the problem with the response is payload size, events can get easily dropped if we don't introduce a flag to limit that, such as https://github.com/getsentry/sentry-dart/issues/624 but that's a different issue.

**Review by marandaneto — APPROVED** [review]

**Comment by ueman** [comment]
I think adding the response instead of the request was an oversight. The SentryHttpClient also adds the request and not the response.

**Pull request merged**
