### PR TITLE
Migration to usage of PlatformView

### LINKED ISSUE #2225: Flutter multiview support
### Platform

Flutter Web

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

```
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.4.1 23E224 darwin-arm64)
    • Flutter version 3.24.0 on channel stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (11 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2
```

### Version

8.7.0

--- 

Flutter 3.24 introduced multiview support in web: https://docs.flutter.dev/platform-integration/web/embedding-flutter-web#enable-multi-view-mode. 
This makes code that uses `WidgetsBinding.instance.window` incompatible with this Flutter version when multiview is enabled. Note that `window` getter was already marked as deprecated and warning is currently ignored in Sentry codebase:
https://github.com/getsentry/sentry-dart/blob/21562c5f6156761d170bd39e03744de9d3f13cdf/flutter/lib/src/widgets_binding_observer.dart#L41-L42

### Steps to Reproduce

1. Use Flutter 3.24 and follow [Flutter docs](https://docs.flutter.dev/platform-integration/web/embedding-flutter-web#enable-multi-view-mode) to enable multiview support in web
2. Setup Sentry
3. Run the web app

Reproduction code: https://github.com/p-mazhnik/sentry-dart/tree/multiview-issue/flutter/example (based on `flutter/example` package from this repo)

### Expected Result

No error, app is launched successfully

### Actual Result

App is not loaded, error in console

```
══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
js_primitives.dart:28 The following assertion was thrown:
js_primitives.dart:28 Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:693:5
js_primitives.dart:28 _window != null
js_primitives.dart:28 "Trying to access the implicit FlutterView, but it is not available.\nNote: the implicit FlutterView
js_primitives.dart:28 is not available in multi-view mode."
js_primitives.dart:28 
js_primitives.dart:28 When the exception was thrown, this was the stack:
js_primitives.dart:28 dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3      throw_
js_primitives.dart:28 dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3       assertFailed
js_primitives.dart:28 lib/_engine/engine/window.dart 693:13                                            get window
js_primitives.dart:28 lib/ui/window.dart 171:45                                                        get window
js_primitives.dart:28 packages/flutter/src/foundation/binding.dart 222:46                              get window
js_primitives.dart:28 packages/sentry_flutter/src/widgets_binding_observer.dart 42:54                  new
js_primitives.dart:28 packages/sentry_flutter/src/integrations/widgets_binding_integration.dart 16:22  call
js_primitives.dart:28 packages/sentry/src/sentry.dart 163:34                                           _callIntegrations
js_primitives.dart:28 dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54               runBody
js_primitives.dart:28 dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5               _async
js_primitives.dart:28 packages/sentry/src/sentry.dart 160:40                                           _callIntegrations
js_primitives.dart:28 packages/sentry/src/sentry.dart 139:17                                           <fn>
js_primitives.dart:28 dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54               runBody
js_primitives.dart:28 dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5               _async
js_primitives.dart:28 packages/sentry/src/sentry.dart 136:43                                           <fn>
js_primitives.dart:28 packages/sentry/src/run_zoned_guarded_integration.dart 75:24                     <fn>
js_primitives.dart:28 dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54               runBody
js_primitives.dart:28 dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5               _async
js_primitives.dart:28 packages/sentry/src/run_zoned_guarded_integration.dart 73:7                      <fn>
js_primitives.dart:28 dart-sdk/lib/async/zone.dart 1399:13                                             _rootRun
js_primitives.dart:28 dart-sdk/lib/async/zone.dart 1301:19                                             run
js_primitives.dart:28 dart-sdk/lib/async/zone.dart 1825:67                                             _runZoned
js_primitives.dart:28 dart-sdk/lib/async/zone.dart 1814:12                                             runZonedGuarded
js_primitives.dart:28 packages/sentry/src/run_zoned_guarded_integration.dart 72:5                      call
js_primitives.dart:28 packages/sentry/src/sentry.dart 150:41                                           _init
js_primitives.dart:28 dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50               <fn>
js_primitives.dart:28 dart-sdk/lib/async/zone.dart 1661:54                                             runUnary
js_primitives.dart:28 dart-sdk/lib/async/future_impl.dart 163:18                                       handleValue
js_primitives.dart:28 dart-sdk/lib/async/future_impl.dart 861:44                                       handleValueCallback
js_primitives.dart:28 dart-sdk/lib/async/future_impl.dart 890:13                                       _propagateToListeners
js_primitives.dart:28 dart-sdk/lib/async/future_impl.dart 666:5                                        [_completeWithValue]
js_primitives.dart:28 dart-sdk/lib/async/future_impl.dart 736:7                                        callback
js_primitives.dart:28 dart-sdk/lib/async/schedule_microtask.dart 40:11                                 _microtaskLoop
js_primitives.dart:28 dart-sdk/lib/async/schedule_microtask.dart 49:5                                  _startMicrotaskLoop
js_primitives.dart:28 dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7               <fn>
js_primitives.dart:28 ════════════════════════════════════════════════════════════════════════════════════════════════════
```

### Are you willing to submit a PR?

None

### PR DESCRIPTION
**Pull request by martinhaintz**
## :scroll: Description
Fix problems using flutter multiview. At the moment the deprecated SingleFlutterWindows is used which is not compatible with multiview.

Here you find the [migration guide](https://docs.flutter.dev/release/breaking-changes/window-singleton)

At the moment you need these additional run args to run a Flutter for MultiView App: `--web-renderer auto`

## :bulb: Motivation and Context
close #2225 

## :green_heart: How did you test it?
Adapted the unittest and adapted the example app, supporting two instances of the sample app.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [ ] All tests passing
- [ ] No breaking changes

## :crystal_ball: Next steps
- chore: refactor sentry-dart to handle multiple views at the same time, therefor we must get rid of the global keys.

### CODE REVIEW

**Comment by martinhaintz** [comment]
I am stuck with this console output:
```
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
Warning: In index.html:48: Manual service worker registration deprecated. Use flutter.js service worker bootstrapping instead. See https://docs.flutter.dev/platform-integration/web/initialization for more details.
This app is linked to the debug service: ws://127.0.0.1:54138/W2P0FZ1IU98=/ws
Debug service listening on ws://127.0.0.1:54138/W2P0FZ1IU98=/ws
Debug service listening on ws://127.0.0.1:54138/W2P0FZ1IU98=/ws
[sentry] [debug] release: sentry_flutter_example@8.8.0
[sentry] [debug] Capture from onError The render object for Listener cannot find ancestor render object to attach to.
The ownership chain for the RenderObject in question was:
  Listener ← SentryUserInteractionWidget ← Container-[GlobalKey#15e26 sentry_widget] ← SentryWidget ← [root]
Try wrapping your widget in a View widget or any other widget that is backed by a RenderTreeRootElement to serve as the root of the render tree.
[sentry] [debug] Capture from onError The Element for ViewCollection cannot be inserted into slot "null" of its ancestor.
The ownership chain for the Element in question was:
  ViewCollection ← MultiViewApp ← DefaultAssetBundle ← RepaintBoundary-[GlobalKey#f9eb4 sentry_screenshot_widget] ← SentryScreenshotWidget ← Listener ← SentryUserInteractionWidget ← Container-[GlobalKey#15e26 sentry_widget] ← SentryWidget ← [root]
This Element allows the creation of multiple independent render trees, which cannot be attached to an ancestor in an existing render tree. However, an ancestor RenderObject is expecting that a child will be attached.
Try moving the subtree that contains the ViewCollection widget into the view property of a ViewAnchor widget or to the root of the widget tree, where it is not expected to attach its RenderObject to its ancestor.
[sentry.flutterError] [error] Exception caught by Flutter framework
                      The render object for Listener cannot find ancestor render object to attach to.
The ownership chain for the RenderObject in question was:
  Listener ← SentryUserInteractionWidget ← Container-[GlobalKey#15e26 sentry_widget] ← SentryWidget ← [root]
Try wrapping your widget in a View widget or any other widget that is backed by a RenderTreeRootElement to serve as the root of the render tree.
[sentry.flutterError] [error] Exception caught by Flutter framework
                      The Element for ViewCollection cannot be inserted into slot "null" of its ancestor.
The ownership chain for the Element in question was:
  ViewCollection ← MultiViewApp ← DefaultAssetBundle ← RepaintBoundary-[GlobalKey#f9eb4 sentry_screenshot_widget] ← SentryScreenshotWidget ← Listener ← SentryUserInteractionWidget ← Container-[GlobalKey#15e26 sentry_widget] ← SentryWidget ← [root]
This Element allows the creation of multiple independent render trees, which cannot be attached to an ancestor in an existing render tree. However, an ancestor RenderObject is expecting that a child will be attached.
Try moving the subtree that contains the ViewCollection widget into the view property of a ViewAnchor widget or to the root of the widget tree, where it is not expected to attach its RenderObject to its ancestor.
[sentry] [warning] Failed to send envelope to Spotlight: ClientException: XMLHttpRequest error., uri=http://localhost:8969/stream
[sentry] [error] Taking screenshot failed.
         View.of() was called with a context that does not contain a View widget.
No View widget ancestor could be found starting from the context that was passed to View.of().
The context used was:
  RepaintBoundary-[GlobalKey#f9eb4 sentry_screenshot_widget](renderObject: RenderRepaintBoundary#fb921 NEEDS-LAYOUT NEEDS-PAINT DETACHED)
This usually means that the provided context is not associated with a View.
         
[sentry] [error] Taking screenshot failed.
         View.of() was called with a context that does not contain a View widget.
No View widget ancestor could be found starting from the context that was passed to View.of().
The context used was:
  RepaintBoundary-[GlobalKey#f9eb4 sentry_screenshot_widget](renderObject: RenderRepaintBoundary#fb921 NEEDS-LAYOUT NEEDS-PAINT DETACHED)
This usually means that the provided context is not associated with a View.
         
[sentry] [warning] Failed to send envelope to Spotlight: ClientException: XMLHttpRequest error., uri=http://localhost:8969/stream
[sentry] [debug] Envelope b8532f950910441d80d0dda863f7b004 was sent successfully to Sentry.
[sentry] [debug] Envelope a49e1602c6054091a9218647ebeb1f23 was sent successfully to Sentry.

======== Exception caught by Flutter framework =====================================================
The following assertion was thrown:
The Element for ViewCollection cannot be inserted into slot "null" of its ancestor. 

The ownership chain for the Element in question was:
  ViewCollection ← MultiViewApp ← DefaultAssetBundle ← RepaintBoundary-[GlobalKey#f9eb4 sentry_screenshot_widget] ← SentryScreenshotWidget ← Listener ← SentryUserInteractionWidget ← Container-[GlobalKey#15e26 sentry_widget] ← SentryWidget ← [root]
This Element allows the creation of multiple independent render trees, which cannot be attached to an ancestor in an existing render tree. However, an ancestor RenderObject is expecting that a child will be attached.

Try moving the subtree that contains the ViewCollection widget into the view property of a ViewAnchor widget or to the root of the widget tree, where it is not expected to attach its RenderObject to its ancestor.
====================================================================================================

======== Exception caught by Flutter framework =====================================================
The following assertion was thrown:
The render object for Listener cannot find ancestor render object to attach to.

The ownership chain for the RenderObject in question was:
  Listener ← SentryUserInteractionWidget ← Container-[GlobalKey#15e26 sentry_widget] ← SentryWidget ← [root]

Try wrapping your widget in a View widget or any other widget that is backed by a RenderTreeRootElement to serve as the root of the render tree.
====================================================================================================
```
Any ideas how to resolve this? @buenaflor @denrase 

ps: if you run the example application, don't forget to add `--web-renderer auto` as run args.

**Comment by denrase** [comment]
Looks like we have more issues in the Sentry/Screenshot Widget. I created a PR with one guard in #2263, but i don't think that is the solution for the problems outlined in https://github.com/getsentry/sentry-dart/issues/1881

I will check out your branch and reproduce this.

**Comment by denrase** [comment]
Ok, on first sight, as we are supporting multiple view, we also need to move to multiple `SentryWidget` widgets wrapping those views. This would mean that we cannot use the static global key of SentryWidget anymore, and need to support multiple ones, just like what you have done with the navigator. Played around a bit and this was my starting point:

```dart
final GlobalKey<NavigatorState> navigatorKey1 = GlobalKey<NavigatorState>();
final GlobalKey<NavigatorState> navigatorKey2 = GlobalKey<NavigatorState>();

final navigatorKeys = [navigatorKey1, navigatorKey2];

final sentryWidgetKey1 = GlobalKey(debugLabel: 'sentry_screenshot_widget_1');
final sentryWidgetKey2 = GlobalKey(debugLabel: 'sentry_screenshot_widget_2');
final sentryWidgetKeys = [sentryWidgetKey1, sentryWidgetKey2];

Future<void> main() async {
  await setupSentry(
    () => runWidget(
      MultiViewApp(
        viewBuilder: (BuildContext context) => SentryWidget(
          globalKey: sentryWidgetKeys[View.of(context).viewId - 1],
          child: DefaultAssetBundle(
            bundle: SentryAssetBundle(),
            child: const MyApp(),
          ),
        ),
      ),
    ),
    exampleDsn,
  );
}
```

At least this is my understanding on the limited exposure i just had to multi-view apps. Wdyt?

**Comment by martinhaintz** [comment]
I tried to make the example app run, with your approach, but ran into the problem, that even if we use multiple globalkeys, the `ScreenshotEventProcessor` and `WidgetEventProcessor` need to access the `currentContext` through the `globalKey` without knowing which `viewId` or which `globalKey` is the correct one. This was currently done with a single `GlobalKey.currentContext`. 

The Main.dart currently looks like this:
```dart
final GlobalKey<NavigatorState> navigatorKey1 = GlobalKey<NavigatorState>();
final GlobalKey<NavigatorState> navigatorKey2 = GlobalKey<NavigatorState>();

final navigatorKeys = [navigatorKey1, navigatorKey2];

final sentryWidgetKey1 = GlobalKey(debugLabel: 'sentry_widget_1');
final sentryWidgetKey2 = GlobalKey(debugLabel: 'sentry_widget_2');
final sentryWidgetKeys = [sentryWidgetKey1, sentryWidgetKey2];

final sentryScreenshotWidgetKey1 =
    GlobalKey(debugLabel: 'sentry_screenshot_widget_1');
final sentryScreenshotWidgetKey2 =
    GlobalKey(debugLabel: 'sentry_screenshot_widget_2');
final sentryScreenshotWidgetKeys = [
  sentryScreenshotWidgetKey1,
  sentryScreenshotWidgetKey2
];

Future<void> main() async {
  await setupSentry(
    () => runWidget(
      MultiViewApp(
        viewBuilder: (BuildContext context) => SentryWidget(
          sentryWidgetGlobalKey: sentryWidgetKeys[View.of(context).viewId - 1],
          sentryScreenshotWidgetGlobalKey:
              sentryScreenshotWidgetKeys[View.of(context).viewId - 1],
          child: DefaultAssetBundle(
            bundle: SentryAssetBundle(),
            child: const MyApp(),
          ),
        ),
      ),
    ),
    exampleDsn,
  );
}
```

`ScreenshotEventProcessor` needs the `currentContext`:
```dart
  /// This is true when the SentryWidget is in the view hierarchy
  bool get _hasSentryScreenshotWidget =>
      sentryScreenshotWidgetGlobalKey.currentContext != null;
```
Also `WidgetEventProcessor` needs the `currentContext`:
```dart
final context = sentryWidgetGlobalKey.currentContext;
```

To access the current `viewId` you have to call `View.of(context).viewId`.

So we would need to save the `viewId` and or the `globalKeys` in the `SentryWidget` and make it accessible. But `ScreenshotEventProcessor` and `WidgetEventProcessor` are instantiated in the `setupSentry` method before the views are even created and then stored in the `SentryOptions` which is global. So we need to somehow add these values afterward for every view.

**Comment by martinhaintz** [comment]
`Flutter 3.13.0` is the first version the `min_version_test` build completes successfully. (without error about missing `platformView.viewId`)
To build the adapted multiview example app, you need at least `Flutter 3.22.0`

Also, if you don't use the `SentryWidget` and do not rely on the single global `NavigatorKey` or find a solution to handle multiple `NavigatorKeys`, the use of `MultiView` is working.

Using the current main branch, without refactoring to the `platformView` another possibility is to disable `integrations.add(WidgetsBindingIntegration());` in `sentry_flutter.dart`. Therefore the deprecated code is not executed and `MultiView` is also working. This also doesn't affect the backward compatibility. The `navigatorKey` problem as written in the last paragraph is also valid for this solution.

Future changes should include, the better handling of multiple views and moving away from using single global keys in sentry, which results in problems if you have them multiple times.

**Comment by martinhaintz** [comment]
Also, have a look at the troubleshooting guide here: 
[PR](https://github.com/getsentry/sentry-docs/pull/11308)
[Guide](https://docs.sentry.io/platforms/flutter/troubleshooting/)

**Comment by buenaflor** [comment]
We've decided not to go ahead with this PR as it's too invasive currently to the SDK given the low priority of the new feature (it's not used very much yet)

The current plan is to document the limitation of our features in combination with multiview embedding. See https://github.com/getsentry/sentry-docs/pull/11308

If in the future we want to support this fully we will revisit this PR.

In that regard, I'm closing this now.

**Pull request closed without merging**
