### PR TITLE
Use `ad-m/github-push-action` for pusshing lint/formatting changes

### LINKED ISSUE #1456: Check why `ananlyze` commit script did not execute on feature branch
### Description

- Check why the commit step was skipped on a feature branch

Bildschirmfoto 2023-05-16 um 14 51 32

- Auto fix swiftlint issues

/cc @marandaneto

### LINKED ISSUE #1469: Use `ad-m/github-push-action` for pusshing lint/formatting changes
### Description

https://github.com/getsentry/sentry-dart/blob/d883d62345e5c21066faf14885eea7afd75b89e1/scripts/commit-formatted-code.sh#L14-L15

The problem is that by pushing this way, CI won't run again since the `bot+github-bot@sentry.io` user has no permissions. This Action actually uses `github_token` and CI will run again after the push.

Right now when CI pushes some fixes, we have to close/reopen the PR to run CI again if needed, which triggers CI.

### PR DESCRIPTION
**Pull request by denrase**
#skip-changelog

## :scroll: Description

Use `ad-m/github-push-action` to push lint/formatting changes

## :bulb: Motivation and Context

Closes #1469
Closes #1456

## :green_heart: How did you test it?

Pushed a format issue which was resolved.

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [ ] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by marandaneto** [comment]
@denrase maybe you can try https://github.com/nektos/act ^^

**Comment by denrase** [comment]
@marandaneto Yeah, should have from the start ^^ 🙈

**Comment by marandaneto** [comment]
> Expected — Waiting for status to be reported

Apparently it did not work?

> Expected — Waiting for status to be reported

CI is still not running after the commit https://github.com/getsentry/sentry-dart/pull/1472/commits/85c4c621b27e1b2f0dcf189e3b5578e0e8a0914b

**Comment by denrase** [comment]
@marandaneto Looks like we have to create/use a personal access token and not use the default `GITHUB_TOKEN `. I don't have access there.

> Hi Stummi,
> 
> Glad to hear you in GitHub Community!
> 
> If an action pushes code using the repository’s GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.
> 
> Please create a personal access token in repo setting(write permission accordingly), replace GITHUB_TOKEN in your ‘inc-counter.yml’, code as below, thanks.
> 
> ```
> - name: Push changes
>       uses: ad-m/github-push-action@master
>       with:
>         github_token: ${{ secrets.PAT}}
> ```
> 
>

**Comment by marandaneto** [comment]
> @marandaneto Looks like we have to create/use a personal access token and not use the default `GITHUB_TOKEN `. I don't have access there.
> 
> > Hi Stummi,
> > Glad to hear you in GitHub Community!
> > If an action pushes code using the repository’s GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.
> > Please create a personal access token in repo setting(write permission accordingly), replace GITHUB_TOKEN in your ‘inc-counter.yml’, code as below, thanks.
> > ```
> > - name: Push changes
> >       uses: ad-m/github-push-action@master
> >       with:
> >         github_token: ${{ secrets.PAT}}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 

@kahest can you check that?

**Comment by kahest** [comment]
> @kahest can you check that?

We don't use PATs anywhere (and I'd like to avoid them), and the action's [`README`](https://github.com/ad-m/github-push-action#inputs) says that `GITHUB_TOKEN` should work unless you push to another repo.

**Comment by denrase** [comment]
@kahest Can't find anything that refers to re-triggering workflows due to push changes. Did you mean the notmal pus? That indeed does work, we are just not re-triggeruing all workflows if something changed. But i think we don't need to do this @marandaneto, as we can just check the format and analyze fixes in the same workflow, or do you have a concern the these might break code? We could also run before all other CI actions.

**Comment by denrase** [comment]
Only found this [discussion](https://github.com/orgs/community/discussions/26220#discussioncomment-3250853), which also describes that a new workflow run will only be triggered with a `PAT`, not with the default `GT`.

**Comment by marandaneto** [comment]
> Only found this [discussion](https://github.com/orgs/community/discussions/26220#discussioncomment-3250853), which also describes that a new workflow run will only be triggered with a `PAT`, not with the default `GT`.

Let's try then :)

**Comment by marandaneto** [comment]
@denrase https://github.com/getsentry/sentry-dart/issues/1469 is now closed since I've not found a way either.
Do we need to open a new PR for https://github.com/getsentry/sentry-dart/issues/1456 or should this be closed as well?
I believe the analyze and commit should still be run, its just a matter if the CI triggers automatically or not, so maybe should should still be addressed.

**Pull request closed without merging**
