### PR TITLE
feat: HttpClient response capture

### LINKED ISSUE #624: Support HTTP response body if sendDefaultPii and maxResponseBodySize are enabled
# Requirement

* We'd like to have full visibility on the logs from the app
* We need to print the full HTTP Request/Response submitted to Sentry
* For whitelisting dozens of apps, it's impossible to double-check the configs for all of them
  * We need ta way to verify how the apps are configured

# Design

* We have mobile apps: Flutter (Android, iOS)
* We have Web apps: Flutter (Progressive Web Apps)
* We have backend services: Java, Golang, Python, Node.js

We need a consistent way to turn HTTP requests `on/off`

### LINKED ISSUE #969: Support `response` field for the `HttpClient` integration
Its been added to `Dio` already -> https://github.com/getsentry/sentry-dart/pull/934
We have to add for the `HttpClient` integration now.

Relates to https://github.com/getsentry/team-mobile/issues/38

This includes deprecating the fields from `response` that are not part of the Response RFC and removing the experimental annotations from the Response class as well.

### PR DESCRIPTION
**Pull request by vaind**
## :bulb: Motivation and Context

closes #969

## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated the docs if needed
- [ ] All tests passing
- [ ] No breaking changes

### CODE REVIEW

**Comment by marandaneto** [comment]
@vaind we've decided that the `body` should not be part of the event because of event limits and PII.
ideally, the body is an attachment, but this still requires an RFC because of PII concerns, frontend changes, etc.
It'd be part of [this feature](https://develop.sentry.dev/sdk/features/#http-client-errors).
I'd not work on this right now unless we want to start with the [RFC](https://github.com/getsentry/rfcs) now.

**Comment by vaind** [comment]
> @vaind we've decided that the `body` should not be part of the event because of event limits and PII. ideally, the body is an attachment, but this still requires an RFC because of PII concerns, frontend changes, etc. It'd be part of [this feature](https://develop.sentry.dev/sdk/features/#http-client-errors). I'd not work on this right now unless we want to start with the [RFC](https://github.com/getsentry/rfcs) now.

What about this RFC that (I'm pretty sure I've seen previously linked from the issue)?  https://github.com/getsentry/rfcs/pull/22

and that DIO integration already does this?

**Comment by marandaneto** [comment]
> > @vaind we've decided that the `body` should not be part of the event because of event limits and PII. ideally, the body is an attachment, but this still requires an RFC because of PII concerns, frontend changes, etc. It'd be part of [this feature](https://develop.sentry.dev/sdk/features/#http-client-errors). I'd not work on this right now unless we want to start with the [RFC](https://github.com/getsentry/rfcs) now.
> 
> What about this RFC that (I'm pretty sure I've seen previously linked from the issue)? [getsentry/rfcs#22](https://github.com/getsentry/rfcs/pull/22)
> 
> and that DIO integration already does this?

That RFC does not contain the `body` because of the given reasons, we'd need to start a new one and get input from different teams, Ingest, security, frontend, etc.
Pretty much proposing a new envelope item type, running data scrubbing, and suggesting frontend changes (how is this going to be displayed with different type of data?)., etc...

**Comment by ueman** [comment]
> and that DIO integration already does this?

The `dio` integration predates all of those RFCs, so the concerns in those RFCs aren't taken into account in that.

**Comment by vaind** [comment]
> That RFC does not contain the `body` because of the given reasons, we'd need to start a new one and get input from different teams, Ingest, security, frontend, etc. Pretty much proposing a new envelope item type, running data scrubbing, and suggesting frontend changes (how is this going to be displayed with different type of data?)., etc...

gotcha. Do you think it makes sense to finish this without the response body then? That's actually already done, I'd just remove the TODO & update test to check the other fields in the response.

**Comment by marandaneto** [comment]
> #624

Yes but this PR should close this [Issue](https://github.com/getsentry/sentry-dart/issues/969) and not [this Issue](https://github.com/getsentry/sentry-dart/issues/624), the later is blocked since we should not offer an option to attach the response body yet.
I'd only set the fields from https://github.com/getsentry/rfcs/pull/22 as well.
Ideally, let's also add `@Deprecated` to the other fields from Response as well, and later fix the new Response protocol for `Dio` as well, does that make sense?

**Comment by vaind** [comment]
replaced by #1095

**Pull request closed without merging**
