### PR TITLE
Add screenshot to `SentryFeedbackWidget`

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

Add the option to add a screenshot `SentryAttachment` to the `SentryFeedbackWidget`

Bildschirmfoto 2024-10-22 um 17 20 47

## :bulb: Motivation and Context

Closes to #1593

## :green_heart: How did you test it?

Unit tests, example app.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by denrase** [comment]
@buenaflor I'm not sure if moving the code that takes the screenshot to the `SentryScreenshotWidget` is even neccessary, as the user facing API is `SentryFlutter.captureFeedback`. Pls add ur 2 cents.

**Comment by buenaflor** [comment]
> I'm not sure if moving the code that takes the screenshot to the SentryScreenshotWidget is even neccessary, as the user facing API is SentryFlutter.captureFeedback. Pls add ur 2 cents.

Can we keep it in the event processor but still capture the correct screen?

How does the JS user feedback behave in comparison

**Review by buenaflor — APPROVED** [review]
lgtm 👍

**Comment by bruno-garcia** [comment]
Let me start with: Thanks! Love this!

Is this on the docs? 
Does it support desktop and mobile? (rather: which platforms does it support?

We'd like to tell a holistic story about our feedback product and capabilities, and include all mobile support. @armcknight added support for iOS, and @romtsn had a PR for Android. More SDKs will come.

cc @jas-kas PM of User Feedback

**Pull request merged**
