### PR TITLE
Send DidBecomeActiveNotification when OOM enabled

### PR DESCRIPTION
**Pull request by philipphofmann**
## :scroll: Description

The OOM code of the Cocoa SDK also relies on the
SentryHybridSdkDidBecomeActive to work properly.
If a user has enableAutoSessionTracking disabled wrong
OOM events would be created.

## :bulb: Motivation and Context
Came up when investigating https://github.com/getsentry/sentry-cocoa/issues/1852.

## :green_heart: How did you test it?
Hard to test as there are no unit tests.

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [x] I updated the docs if needed
- [ ] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Review by marandaneto — APPROVED** [review]
Makes sense, thanks @philipphofmann

**Comment by kuhnroyal** [comment]
Is this related to the huge amount of OOMs on iOS?

**Comment by kuhnroyal** [comment]
Nvm, you even linked it :) Sorry

**Comment by philipphofmann** [comment]
@kuhnroyal, only if you have `enableAutoSessionTracking` disabled.

**Comment by kuhnroyal** [comment]
> @kuhnroyal, only if you have `enableAutoSessionTracking` disabled.

I checked but this is enabled by default and I have not changed it.

**Pull request merged**
