### PR TITLE
Added missing Contexts to Event.copyWith()

### PR DESCRIPTION
**Pull request by jamieastley**

### CODE REVIEW

**Comment by jamieastley** [comment]
@googlebot  I signed it!

**Review by bruno-garcia — APPROVED** [review]
It's all shallow copying which could be particularly problematic for `Contexts` given that this data will be made available through [Sentry's Scope](https://docs.sentry.io/enriching-error-data/scopes/) which can be mutated while an event is queued for submission.

Since this is at least keeping it consistent it makes sense to me to merge it but I believe we need to change this approach.

@yjbanov thoughts?

**Comment by bruno-garcia** [comment]
@jamie1192 if you can please add the entry to the changelog, we can get this merged.
More changes will land before 4.0.0 comes out though, likely the `Scope` class included and avoid breaking changes for a while after that.

**Comment by jamieastley** [comment]
no problem @bruno-garcia , all done.

**Comment by bruno-garcia** [comment]
Thanks you @jamie1192

**Pull request merged**
