### PR TITLE
Fix: Flutter Beta CI

### PR DESCRIPTION
**Pull request by ueman**
## :scroll: Description
CI fails on Flutter beta channel, this PR fixes that

## :bulb: Motivation and Context
https://github.com/getsentry/sentry-dart/issues/377

## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated the docs if needed
- [ ] All tests passing
- [ ] No breaking changes

### CODE REVIEW

**Comment by ueman** [comment]
@marandaneto 
iOS complains now about missing provisioning profiles: https://github.com/getsentry/sentry-dart/pull/378/checks?check_run_id=2165314911
and I'm not able to reprduce it locally.
Do you have any idea?

**Comment by marandaneto** [comment]
> @marandaneto
> iOS complains now about missing provisioning profiles: https://github.com/getsentry/sentry-dart/pull/378/checks?check_run_id=2165314911
> and I'm not able to reprduce it locally.
> Do you have any idea?

no idea, it should not have been an issue because it compiles with `--no-codesign` right? unless this is not related with provisioning profiles.
what has changed in the beta channel? :( maybe the flutter repo already has issues and possibly a workaround?

**Comment by ueman** [comment]
> > @marandaneto
> > iOS complains now about missing provisioning profiles: https://github.com/getsentry/sentry-dart/pull/378/checks?check_run_id=2165314911
> > and I'm not able to reprduce it locally.
> > Do you have any idea?
> 
> no idea, it should not have been an issue because it compiles with `--no-codesign` right? unless this is not related with provisioning profiles.
> what has changed in the beta channel? :( maybe the flutter repo already has issues and possibly a workaround?

I think the provisioning message is just a wrong error message and the real error is that the GeneratedPluginRegistrant on iOS aren't generated. 

Changes between stable and beta https://github.com/flutter/flutter/compare/2.0.3...2.1.0-12.2.pre

**Comment by ueman** [comment]
I raised an issue on the Flutter repo: https://github.com/flutter/flutter/issues/78785

**Comment by marandaneto** [comment]
> I raised an issue on the Flutter repo: [flutter/flutter#78785](https://github.com/flutter/flutter/issues/78785)

let's `exclude` out the `beta` channel from CI for iOS right now so we get CI happy till getting an answer on that issue.
The Android issue seems to be unrelated though, so we need to check this one out.

**Pull request closed without merging**
